### ISSUE TITLE
Arel Model.arel_table.project(stuff) vs Model.select(stuff) 

### ISSUE THREAD

**Issue by nimmolo** [camertron/arel-helpers#52]
Hi, Thank you for maintaining this awesome gem.
Sorry this is not an issue, just a request for clarification that's hopefully easy to answer.

The Arel `project` method would appear to be one case where `ArelHelpers::ArelTable` does not eliminate the need to call `.arel_table`, and that is OK with me. 

But can you pretty much always write `Model.select(whatever)` instead of `Model.arel_table.project(whatever)`? Is there a difference? I find using the helpers are blurring the line for me between whether i am aware that i'm writing ActiveRecord, or Arel.

**Comment by camertron** [comment]
Hey @nimmolo,

My understanding is that ActiveRecord uses Arel internally to build queries, and offers a number of convenience methods on top of Arel to make it friendlier to use. Arel is actually quite a bit more powerful than ActiveRecord though, and there are quite a few classes of query that simply aren't possible with ActiveRecord alone. The helpers in this gem are designed to paper over some of the incompatibilities between the two libs in order to allow you to leverage more of Arel in your code, which is probably why the line seems blurry to you. I wish there weren't a line at all, but the Rails core team has made it pretty clear they want Arel to remain a private API.

To answer your actual question, `Model.select(whatever)` is ActiveRecord, and `Model.arel_table.project(whatever)` is Arel (I think you can still write `Model.arel_table.select(whatever)` as an alias for `project`, but that may not be true anymore).

The two statements aren't necessarily equivalent. As far as I know, you can't use `project` to actually fire off a query. However, they are equivalent in that they will result in the same columns being selected. In fact, ActiveRecord uses `project` [under the hood](https://github.com/rails/rails/blob/5fdbd217d18302cd277f80a9ba7fd567844ec324/activerecord/lib/active_record/relation/query_methods.rb#L1477) to build `SELECT` statements.

Things get more complicated if you want to, for example, alias a column:

```ruby
# pure ActiveRecord
Model.select("column_name AS alias_name")

# ActiveRecord + Arel
Model.select(Model.arel_table[:column_name].as(:alias_name))
```

Notice that ActiveRecord forces you to use a string while Arel provides a nice `as` method.

I hope that helps 😄

**Comment by nimmolo** [comment]
Thank you for that thorough explanation and background, i've read it several times to let it sink in. (That answer was above and beyond and you certainly don't need to respond further... I know you're busy. I'll close the issue too.)

Where i get tripped up, remembering whether i'm in AR or Arel, is knowing when i'm firing the query, and when i'm just describing it, without trying it over and over in Rails console and observing the results. It seems some model methods can be used for both "firing" and "describing". 

Like,  i can give`connection.select_values` either AR (code that fires a query.to_sql) or Arel (code that describes a query.to_sql), as long as I append `.to_sql`. For example here, `Model.select().to_sql`:
```ruby
query = Model.select(:id).where(Model[:author].eq(author)).order(Model[:created_at].desc)
#<Model:0x000055ebf014aac8> ...fires query returning activerecords
values = Model.connection.select_values(query.to_sql)
#[23,52,346]
```
I would imagine the first line with `Model.select` fires the query right away, and I guess `select_values` is doing more like a `pluck` on the results. 

But `Model.arel_table.project` works to get the values, too:
```ruby
query = Model.arel_table.project(Model[:id]).where(Model[:author].eq(author)).order(Model[:created_at].desc)
# does not fire query, but connection.select_values somehow gets the goods anyway
values = Model.connection.select_values(query.to_sql)
#[23,52,346]
```
Is one of these preferable? Is the Arel more chainable? My impression is that you can chain mixing Arel and AR almost indiscriminately, as long as you pay attention to the syntax inside your parentheses and use `.to_sql` at the end...?

**Comment by camertron** [comment]
It's no problem, happy to help 😄 

> Where i get tripped up, remembering whether i'm in AR or Arel, is knowing whether i'm firing the query, or i'm just describing it, without trying it over and over in Rails console and observing the results. It seems some methods can be used for both "firing" and "describing".

Right yeah, it can be difficult to know when a query will execute vs return an `ActiveRecord::Relation` object you can chain additional query statements on. It's even more complicated in a Rails console or IRB session because the return value is automatically printed out using `#inspect` which executes the query automatically, sometimes before you're ready. A trick I use in the console is to stick a `;nil` at the end of the line so only a `nil` gets printed and no query gets executed.

To complicate things even _more_, there are certain so-called "terminal" methods like `#count`, `#exists?` etc, that run the query immediately and return a number, true/false, etc.

As a general rule, any time you call a method on a model's class, eg `Model.select`, `Model.where`, etc), that's ActiveRecord and will result in actually executing the query. Any methods called on an instance of `Arel::Table` won't. Arel's job is to let you write SQL statements in Ruby, while ActiveRecord's job is to execute those SQL statements and hand you back the results as a set of objects.

> I would imagine the first line with `Model.select` fires the query right away, and I guess `select_values` is doing more like a `pluck` on the results.

As you've noted, both Arel query objects and `ActiveRecord::Relation`s can be turned into raw SQL statements via `#to_sql`. I believe `connection.select_values` accepts a string (the result of `#to_sql`), executes it against the database, then type casts the results. The behavior is certainly like `#pluck`, but you're essentially circumventing ActiveRecord here.

> Is one of these preferable?

I personally try to use ActiveRecord APIs whenever I can, because 1) Arel is technically a private API and can change at any time, 2) there's a much greater chance it'll work without a lot of experimentation, and 3) generally ActiveRecord APIs are much less verbose.

For example, rather than writing this:

```ruby
Post.joins(
  Post.arel_table.join(Comment.arel_table)
    .on(Post[:id].eq(Comment[:post_id]))
    .join_sources
)
```

it's a lot nicer to let ActiveRecord do the ID matchup for me and write this:

```ruby
Post.joins(:comments)
```

It's even nicer when I'm trying to join three tables together (posts have comments, and comments have authors):

```ruby
Post.joins(comments: :authors)
```

^ the equivalent SQL/Arel statement is absolutely possible, but requires a lot more effort to write.

> Is the Arel more chainable?

Because ActiveRecord often returns `ActiveRecord::Relation` objects, both are pretty chainable. Again, I only reach for Arel when ActiveRecord's API is too limiting. In other words, the big concern is more flexibility than chainability.

> My impression is that you can chain mixing Arel and AR almost indiscriminately, as long as you pay attention to the syntax inside your parentheses and use .to_sql at the end...?

Hmm, sort of. ActiveRecord and Arel are super compatible about 80% of the time, and then completely incompatible the other 20%. Notice in the example above that I had to call `#join_sources` in order to pass the Arel-constructed join statement to ActiveRecord. That's because ActiveRecord doesn't support passing an Arel object to `#join` for some reason. Stuff like that.

Yeah, `#to_sql` is a nice escape hatch I've had to use a few times when the libraries refuse to talk to each other. Unfortunately that also means you're often executing the query with something like `connection.select_values` or `connection.execute`, the latter of which will return an array of arrays instead of model instances. Hopefully that's not necessary for all but the most complex of queries.

**Comment by nimmolo** [comment]
Thank you Cameron, this is very helpful and i've referred to it many times already :))
